### ISSUE TITLE
When Exchanger Simex/Dobi is Ready to trade in it?

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/ddk_deploy#43]
Now in may 2019, We are still waiting

**Comment by indigoram89** [comment]
Simex is ready for integration and waiting for production mode.

**Comment by Ginds** [comment]
So when the produtction mode is done?

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Please follow latest announcement on DDK Official Blog from here https://announcements.ddkoin.com/ OR you can refer to any TD (Trusted Delegate) to get latest information and updates. For review latest list of TD from your country, can be refer from this link : https://ddkoin.com/trusted-delegates.

For your question, we have completed the SDK requested by SIMEX exchanger PHP SDK for DDK NODE (https://github.com/AraiEzzra/DDKCORE.SDK.PHP) and while for DOBI they are requesting the JAVA SDK (https://github.com/AraiEzzra/DDKCORE.SDK.JAVA) for their exchanger. Both exchanger have received codes for the DDK NODE and waiting for the BETA MAINNET phase to complete. We need BETA phase so that all problems identified about PREORDER users can be corrected before the start of MAINNET. 

Regards

**Comment by Ginds** [comment]
Thankyou about the info, I wish the best for beta Mainnet. So that this project can be done and no delay again. Good Luck
